// Generated by CoffeeScript 1.7.1
(function() {
  if (typeof sjcl === "undefined" || sjcl === null) {
    throw new Error('No sjcl library found!');
  }

  if (sjcl.keyexchange.ssrp != null) {
    throw new Error('Overriding sjcl.keyexchange.ssrp!');
  }

  sjcl.keyexchange.ssrp = {
    count: 2048,
    _serialize: function(point) {
      point = point.get();
      point = sjcl.codec.base64.fromBits(point.x.concat(point.y));
      return point;
    },
    _unserialize: function(curve, point) {
      return new sjcl.ecc.elGamal.publicKey(curve, sjcl.codec.base64.toBits(point));
    },
    _generatePrivateKey: function(password, salt, curve) {
      var length, x;
      length = Math.floor((curve.r.bitLength() - 1) / 8);
      x = sjcl.misc.pbkdf2(password, salt, this.count, length);
      return new sjcl.bn(x);
    },
    makeVerifier: function(username, password, curve) {
      var salt, x;
      curve = curve || 256;
      if ("number" === typeof curve) {
        curve = sjcl.ecc.curves['c' + curve];
        if (curve == null) {
          throw new Error('No such curve!');
        }
      }
      salt = sjcl.random.randomWords(2, 10);
      x = this._generatePrivateKey(username + '.' + password, salt, curve);
      return this._serialize(curve.G.mult(x));
    },
    makeChallenge: function(curve) {
      var kp;
      kp = sjcl.ecc.elGamal.generateKeys(curve);
      kp.pub = this._serialize(kp.pub);
      return kp;
    },
    makeResponse: function(username, password, salt, chall, curve) {
      var x;
      x = this._generatePrivateKey(username + '.' + password, salt, curve);
      chall = this._unserialize(chall);
      return this._serialize(chall.mult(x));
    },
    verify: function(sec, verifier, resp) {
      var rightResp;
      verifier = this._unserialize(verifier);
      rightResp = this._serialize(verifier.mult(sec));
      return rightResp === resp;
    }
  };

}).call(this);
